function readingEvents(){eBook.addEventListener("click",nextPage)}function endOfChapter(){HI6MA.readingBook=!1,HI6MA.openChapter=!0,eBook.setAttribute("style","transform: translateX(-30px)")}function loadBook(){location.hash=HI6MA.series+"_"+HI6MA.chapter,totalPages=1,page=1,eBook.innerHTML="",leftM=0,imgSrc="i/"+HI6MA.series+"/"+HI6MA.chapter_full+"/"+pformat(page)+".png"
var e=document.createElement("img")
e.setAttribute("src",imgSrc),e.setAttribute("id","pagePNG"+page),e.setAttribute("onerror","removeBroken(this)"),eBook.appendChild(e),imgSrc="i/"+HI6MA.series+"/"+HI6MA.chapter_full+"/"+pformat(page)+".jpg","/"+pformat(HI6MA.currentPage)+".jpg"
var e=document.createElement("img")
e.setAttribute("src",imgSrc),e.setAttribute("id","pageJPG"+page),e.setAttribute("onerror","removeBroken(this)"),eBook.appendChild(e),document.querySelector("#pagePNG1").classList.add("currentPage"),document.querySelector("#pageJPG1").classList.add("currentPage"),loadImg(page)}function loadImg(e){document.querySelector("#pagePNG"+e).onload=function(){appendImg(e)},document.querySelector("#pageJPG"+e).onload=function(){appendImg(e)}}function appendImg(e){e++,imgSrc="i/"+HI6MA.series+"/"+HI6MA.chapter_full+"/"+pformat(e)+".png"
var t=document.createElement("img")
t.setAttribute("src",imgSrc),t.setAttribute("id","pagePNG"+e),t.setAttribute("onerror","removeBroken(this)"),eBook.appendChild(t),imgSrc="i/"+HI6MA.series+"/"+HI6MA.chapter_full+"/"+pformat(e)+".jpg"
var t=document.createElement("img")
t.setAttribute("src",imgSrc),t.setAttribute("id","pageJPG"+e),t.setAttribute("onerror","removeBroken(this)"),eBook.appendChild(t),HI6MA.readingBook&&loadImg(e),totalPages++,title(HI6MA.currentPage,totalPages),readingEvents()}function removeBroken(e){try{e.parentNode.removeChild(e)}catch(t){}}function pformat(e){return 10>e?"00"+e:100>e?"0"+e:e}function checkKey(e){e=e||window.event,eHTML.classList.contains("viewing")&&("37"==e.keyCode?nextPage():"39"==e.keyCode&&prevPage())}function title(e,t){document.title="["+e+"/"+t+"] "+HI6MA.series_full+" | "+document.domain}function truncate(e){return e.replace(/\W/g,"")}var domain=document.domain
"www"===domain.substr(0,3)&&(domain=domain.substr(4,domain.length))
var HI6MA=new Vue({el:"#menu",data:{booklist:books,openChapter:!1,readingBook:!1,showSeries:!0,hideiFrame:!0,series_full:"",series:"",chapter:"",chapter_full:"",domain:domain,currentPage:1,loadedChapters:[],book:""},methods:{bookCover:function(e){var t="i/"+this.booklist[e].folder
return t+="/cover.jpg"},openBook:function(e,t){window.scrollTo(0,0),this.book=t,this.openChapter=!0,this.showSeries=!1,this.loadedChapters=this.booklist[e].chapters,this.series=this.booklist[e].folder,this.series_full=this.booklist[e].name},closeBook:function(){this.openChapter=!1,this.showSeries=!0,this.loadedChapters=[""]},loadChapter:function(e){this.chapter_full=this.loadedChapters[e]
var t=this.loadedChapters[e]
this.chapter=t.replace(/\W/g,""),this.readingBook=!0,this.openChapter=!1,loadBook(),readingEvents(),window.scrollTo(0,0)},returnToSeriesList:function(){this.readingBook=!1,this.showSeries=!0,location.hash="",eBook.innerHTML="",eBook.setAttribute("style","transform: translateX(0px)"),this.currentPage=1,document.title=domain},truncateChapter:function(e){var t=this.loadedChapters[e]
return t.replace(/\W/g,"")},checkEmpty:function(e){return void 0==e||""==e?!1:!0},previousPage:function(){prevPage()}}}),sheet=document.styleSheets[document.styleSheets.length-1]
sheet.insertRule("#book img{max-width:"+(window.innerWidth-30)+"px;}",1),sheet.insertRule("@media (orientation: portrait), (max-width: 750px){#book img{max-width:"+window.innerWidth+"px !important;}}",1)
var leftM=0,eHeader=document.getElementsByTagName("header")[0],eSidebar=document.getElementsByTagName("sidebar")[0],eBack=document.getElementById("back"),eSeries=document.getElementById("series"),eBook=document.getElementById("book"),eTitle=document.getElementById("title"),eHeadTitle=document.getElementById("headTitle"),eHTML=document.querySelector("html"),eFooter=document.getElementsByTagName("footer")[0],domain=document.domain
"www"===domain.substr(0,3)&&(domain=domain.substr(4,domain.length)),series="",chapter="",series_r="",chapter_r=""
var seriesList=document.querySelectorAll("#series .book"),URL=document.URL
if(URL=URL.split("#"),void 0!=URL[1]&&URL[1].length>2){"/"==URL[1].substr(0,1)&&(URL[1]=URL[1].substr(1)),URL[1]=URL[1].split("#"),URL[1]=URL[1][URL[1].length-1]
var urlX=URL[1].split("_")
HI6MA.series=urlX[0],HI6MA.chapter=urlX[1],HI6MA.readingBook=!0,HI6MA.openChapter=!1,HI6MA.showSeries=!1,eBook.setAttribute("style","transform: translateX(0px)")
for(var i=0;i<HI6MA.booklist.length;i++)if(HI6MA.booklist[i].folder==HI6MA.series){HI6MA.series_full=HI6MA.booklist[i].name,HI6MA.loadedChapters=HI6MA.booklist[i].chapters
for(var j=0;j<HI6MA.booklist[i].chapters.length;j++)truncate(HI6MA.booklist[i].chapters[j])==HI6MA.chapter&&(HI6MA.chapter_full=HI6MA.booklist[i].chapters[j])}leftM=0,HI6MA.currentPage=1,loadBook()}var nextPage=function(e){window.scrollTo(0,0)
try{eBook.removeEventListener("click",nextPage),leftM+=document.querySelector(".currentPage").offsetWidth
try{document.querySelector("#pagePNG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}try{document.querySelector("#pageJPG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}HI6MA.currentPage++
try{document.querySelector("#pagePNG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}try{document.querySelector("#pageJPG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}eBook.addEventListener("click",nextPage),eBook.setAttribute("style","transform: translateX("+leftM+"px)")}catch(e){endOfChapter()}title(HI6MA.currentPage,totalPages)},prevPage=function(){if(HI6MA.currentPage>1){try{eBook.removeEventListener("click",nextPage),leftM-=document.querySelector(".currentPage").previousElementSibling.offsetWidth
try{document.querySelector("#pagePNG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}try{document.querySelector("#pageJPG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}HI6MA.currentPage--
try{document.querySelector("#pagePNG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}try{document.querySelector("#pageJPG"+HI6MA.currentPage).classList.toggle("currentPage")}catch(e){}eBook.addEventListener("click",nextPage),eBook.setAttribute("style","transform: translateX("+leftM+"px)")}catch(e){}title(HI6MA.currentPage,totalPages)}}
document.onkeydown=checkKey,window.onload=function(){var e=0,t=new FontFace("lato",["url(https://fonts.gstatic.com/s/lato/v11/MDadn8DQ_3oT6kvnUq_2r_esZW2xOQ-xsNqO47m55DA.woff2)","url(https://fonts.gstatic.com/s/lato/v11/MgNNr5y1C_tIEuLEmicLmwLUuEpTyoUstqEm5AMlJo4.woff2)"],{}),o=new FontFace("latoBold","url(https://fonts.gstatic.com/s/lato/v11/MgNNr5y1C_tIEuLEmicLmwLUuEpTyoUstqEm5AMlJo4.woff2)",{weight:"bold"})
t.load().then(function(t){e++,2===e&&r()}),o.load().then(function(t){e++,2===e&&r()})
var r=function(){document.fonts.add(t),document.fonts.add(o),document.body.className+=" fontLoaded"}}
